version: '3.4'

services:
  crudapi:
    image: crudapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    extra_hosts:
      - "uat-s3.universityapp.net:172.29.106.101"
    env_file:
      - .env
    volumes:
      - .:/go/src/app

