
GET http://localhost:8080/user

###

POST http://localhost:8080/user
Content-Type: application/json

{
    "id": "3",
    "username": "GG33",
    "role": "Admi2n"
  },

###

DELETE http://localhost:8080/user/2
