
GET http://localhost:8080/profile

###

GET http://localhost:8080/profile/3

###

POST http://localhost:8080/profile
Content-Type: application/json

	
{
   "first_name": "JACKKENG",
    "last_name": "JACKKENG",
    "position_id": 1,
    "university":"5",
    "address_home":"NEWYORK",
    "address_work":"WORLD",
    "email":"jkeng@gmail.com",
    "phone_number":"9999",
    "created_by": "Champlnwza007",
    "updated_by": "Champlnwza007"
}



###
PUT http://localhost:8080/profile/4
Content-Type: application/json


{
    "first_name": "JACKKING",
    "last_name": "JACKKENG",
    "position_id": 1,
    "university":"1",
    "address_home":"NEWYORK",
    "address_work":"WORLD",
    "email":"jkeng@gmail.com",
    "phone_number":"9999",
    "created_by": "Champlnwza007",
    "updated_by": "Champlnwza007"
}
###
DELETE http://localhost:8080/profile/4
###
DELETE http://localhost:8080/profile/all



#