
GET http://localhost:8080/assessment

###

GET http://localhost:8080/assessment/1

###

POST http://localhost:8080/assessment
Content-Type: application/json

	
{
    "degree_type": "เอก",
    "degree_program": "computer",
    "degree_university": "KK",
    "profile_id": 2,
    "created_by": "Champlnwza007",
    "updated_by": "Champlnwza007"
}



###
PUT http://localhost:8080/assessment/7
Content-Type: application/json

{
    "degree_type": "นายสาว",
    "degree_program": "computer",
    "degree_university": "KK",
    "profile_id": 1,
    "created_by": "Champlnwza007",
    "updated_by": "Champlnwza007"
}
###
DELETE http://localhost:8080/assessment/7
###
DELETE http://localhost:8080/assessment/all



