
GET http://localhost:9000/degree

###

GET http://localhost:9000/degree/1

###

POST http://localhost:9000/degree
Content-Type: application/json

	
{
    "degree_type": "โท",
    "degree_program": "computer",
    "degree_university": "KK",
    "profile_id": 1,
    "created_by": "Champlnwza007",
    "updated_by": "Champlnwza007",
    "activated": true
}


###
PUT http://localhost:9000/degree/7
Content-Type: application/json

{
    "degree_type": "นายสาว",
    "degree_program": "computer",
    "degree_university": "KK",
    "profile_id": 1,
    "created_by": "Champlnwza007",
    "updated_by": "Champlnwza007"
    "isActivated": true
}
###
DELETE http://localhost:9000/degree/7
###
DELETE http://localhost:9000/degree/all



# [
#   {
#     "id": 1,
#     "position": "ศาสตราจารย์เกียรติคุณ",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:00:23.918529Z",
#     "updated_at": "2023-03-27T17:00:23.918529Z"
#   },
#   {
#     "id": 2,
#     "position": "ศาสตราจารย์ ดร.",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:35.630697Z",
#     "updated_at": "2023-03-27T17:01:35.630697Z"
#   },
#   {
#     "id": 3,
#     "position": "ศาสตราจารย์",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:35.69981Z",
#     "updated_at": "2023-03-27T17:01:35.69981Z"
#   },
#   {
#     "id": 4,
#     "position": "ศาสตราจารย์",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:35.768835Z",
#     "updated_at": "2023-03-27T17:01:35.768835Z"
#   },
#   {
#     "id": 5,
#     "position": "รองศาสตราจารย์",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:35.83767Z",
#     "updated_at": "2023-03-27T17:01:35.83767Z"
#   },
#   {
#     "id": 6,
#     "position": "ผู้ช่วยศาสตราจารย์ ดร.",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:35.906158Z",
#     "updated_at": "2023-03-27T17:01:35.906158Z"
#   },
#   {
#     "id": 7,
#     "position": "ผู้ช่วยศาสตราจารย์",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:35.97475Z",
#     "updated_at": "2023-03-27T17:01:35.97475Z"
#   },
#   {
#     "id": 8,
#     "position": "ดร.",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:36.046396Z",
#     "updated_at": "2023-03-27T17:01:36.046396Z"
#   },
#   {
#     "id": 9,
#     "position": "อาจารย์",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:36.115528Z",
#     "updated_at": "2023-03-27T17:01:36.115528Z"
#   },
#   {
#     "id": 10,
#     "position": "อื่น ๆ ",
#     "created_by": "champInwZa007",
#     "updated_by": "champInwZa007",
#     "created_at": "2023-03-27T17:01:36.184115Z",
#     "updated_at": "2023-03-27T17:01:36.184115Z"
#   }
# ]