
GET http://localhost:9000/exploration

###

GET http://localhost:9000/exploration/3

###

POST http://localhost:9000/exploration
Content-Type: application/json

	
{
    "explore_name":"TEST",
    "explore_year":"TEST",
    "explore_detail":"TEST",
    "profile_id": 1,
    "activated": true,
    "created_by": "Champlnwza008",
    "updated_by": "Champlnwza008"
}



###
PUT http://localhost:9000/exploration/1
Content-Type: application/json

{ 
  "explore_name":"TEST1",
    "explore_year":"TEST",
    "explore_detail":"TEST",
    "profile_id": 1,
    "activated": true,
    "created_by": "Champlnwza008",
    "updated_by": "Champlnwza008"
}

###
DELETE http://localhost:9000/exploration/1
###
DELETE http://localhost:9000/exploration/all



