
GET http://localhost:8080/profile_attach

###

GET http://localhost:8080/profile_attach/3

###

POST http://localhost:8080/profile_attach
Content-Type: application/json


{
    "file_name":"TEST",
    "file_action":"TEST",
    "file_storage":"TEST",
    "profile_id": 1,
    "created_by": "Champlnwza008",
    "updated_by": "Champlnwza008"
}



###
PUT http://localhost:8080/profile_attach/1
Content-Type: application/json

{ 
    "file_name":"TEST",
    "file_action":"TEST1150",
    "file_storage":"TEST",
    "profile_id": 1,
    "created_by": "Champlnwza008",
    "updated_by": "Champlnwza008"
}

###
DELETE http://localhost:8080/profile_attach/1
###
DELETE http://localhost:8080/profile_attach/all



