
GET http://localhost:9000/program

###

GET http://localhost:9000/program/3

###

POST http://localhost:9000/program
Content-Type: application/json

	
{
    "Program_name": "TOSLOW",
    "Profile_id"  : 1,
     "activated": true,
    "created_by": "Champlnwza008",
    "updated_by": "Champlnwza008"
}



###
PUT http://localhost:9000/program/2
Content-Type: application/json


{ "Program_name": "TOSLOW",
    "Profile_id"  : 3,
     "activated": true,
    "created_by": "Champlnwza009",
    "updated_by": "Champlnwza009"
}
###
DELETE http://localhost:9000/program/1
###
DELETE http://localhost:9000/program/all



# 