
GET http://localhost:8080/api/v1/researcher/profile_detail/1
###
POST http://localhost:8080/api/v1/researcher/profile
Content-Type: application/json

{
    "first_name": "Jacky",
    "last_name": "KAK",
    "position_id": 1,
    "address_home": "178-180",
    "address_work": "178-180",
    "email": "jackKAK@email.com",
    "phone_number": "123-456-7890",
    "degree": [
        {
        "degree_type": "โท",
        "degree_program": "Computer Science",
        "degree_university": "KMUTNB"
        },
        {
        "degree_type": "ตรี",
        "degree_program": "Computer Science",
        "degree_university": "KMUTNB"
        }
    ],
    "program": [
        {
        "program_name": "Coding Bootcamp",
        "university": "MIT"
        },
        {
        "program_name": "Leadership Development",
        "university": "Wharton School of the University of Pennsylvania"
        }
    ],
    "experience": [
        {
        "experience_type": "Internship",
        "experience_start": "2018-05-01",
        "experience_end": "2018-08-31",
        "experience_university": "Google",
        "experience_remark": "Developed a web application for tracking employee performance"
        },
        {
        "experience_type": "Full-time",
        "experience_start": "2019-01-01",
        "experience_end": null,
        "experience_university": "Microsoft",
        "experience_remark": "Led a team of software engineers in developing a new feature for a cloud-based productivity tool"
        }
    ],
    "explore": [
        {
        "explore_name": "Study Abroad",
        "explore_year": "2017",
        "explore_detail": "Studied computer science and economics at the University of Tokyo for one semester"
        },
        {
        "explore_name": "Volunteering",
        "explore_year": "2019",
        "explore_detail": "Organized a charity event for a local food bank, raising $10,000 in donations"
        }
    ],
    "attach": [
        {
        "file_name": "resume.pdf",
        "file_action": "Download"
        },
        {
        "file_name": "cover_letter.docx",
        "file_action": "Download"
        }
    ]
}



###

POST http://localhost:8080/researcher/profile_detail
Content-Type: application/json


{
  "profile_id": 1,
  "first_name": "JACKKENG",
  "last_name": "JACKKENG",
  "university": "5",
  "address_home": "NEWYORK",
  "address_work": "WORLD",
  "email": "jkeng@gmail.com",
  "phone_number": "9999",
  "degree": [
    {
      "id": 1,
      "degree_type": "ตรี",
      "degree_program": "computer",
      "degree_university": "KK"
    },
    {
      "id": 2,
      "degree_type": "โท",
      "degree_program": "computer",
      "degree_university": "KK"
    },
    {
      "id": 3,
      "degree_type": "เอก",
      "degree_program": "computer",
      "degree_university": "KK"
    }
  ],
  "position": [
    {
      "position_id": 1,
      "position_name": "นางสาว"
    }
  ],
  "program": [
    {
      "program_id": 1,
      "program_name": "TOSLOW"
    }
  ],
  "experience": [
    {
      "experience_id": 1,
      "experience_type": "TESTEX",
      "experience_start": "TEST",
      "experience_end": "TEST",
      "experience_university": "TEST",
      "experience_remark": "TEST"
    }
  ],
  "attach": [
    {
      "file_id": 1,
      "file_name": "TEST",
      "file_action": "TEST",
      "file_storage": "TEST"
    }
  ],
  "explore": [
    {
      "explore_id": 1,
      "explore_name": "TEST",
      "explore_year": "TEST",
      "explore_detail": "TEST"
    }
  ]
}



